#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/commands/init.sh"
source "$SCRIPT_DIR/commands/status.sh"
source "$SCRIPT_DIR/commands/history.sh"
source "$SCRIPT_DIR/commands/help.sh"
source "$SCRIPT_DIR/commands/logr.sh"
source "$SCRIPT_DIR/commands/utils.sh"

case "$1" in
	init)
	    init_onlabiee
	    ;;
	status)
	    show_status
	    ;;
	history)
	    show_history
	    ;;
	utils)                    # Temp command to test working
	    find_project
	    ;;
	help|-h|--help)
	    show_help
	    ;;
	"")
	    start_logr
	    ;;
	*)
	    echo "Unknown command: $1"
	    echo "Run 'onlabiee help' for usage"
	    exit 1
	    ;;
esac
