#!/usr/bin/env bash

set -e

INSTALL_DIR="/usr/local/lib/onlabiee"
BIN_FILE="/usr/local/bin/onlabiee"

if [ -f "$BIN_FILE" ] && [ -d "$INSTALL_DIR" ]; then
    echo "Uninstalling onlabiee......"
    sudo rm "$BIN_FILE"
    sudo rm -rf "$INSTALL_DIR"
    echo "Uninstalled onlabiee"
else
    echo "onlabiee not installed..."
fi
