#!/usr/bin/env bash

set -e

EXECUTABLE="onlabiee"
INSTALL_DIR="usr/local/bin"

if [ -f "$INSTALL_DIR/$EXECUTABLE" ]; then
    echo "Uninstalling onlabiee...."
    sudo rm "$INSTALL_DIR/$EXECUTABLE"
    echo "Uninstalled onlabiee"
else
    echo "onlabiee not installed..."
fi
